# application.yml
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.94.152.107:3306/blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456qqQQ.
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    solr:
      host: http://192.144.131.25:8983/solr
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: kdrozgxcnlfjbdfg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: 917708203@qq.com

  servlet:
    multipart:
      enabled: true
      max-file-size: 220MB  #单个文件的最大上限
      max-request-size: 220MB #单个请求的文件总大小上限


mybatis:
  type-aliases-package: com.ndsc.blog.entity
  mapper-locations: classpath:mapping/*Mapper.xml



#showSql
logging:
  level:
    com:
      example:
        mapper: debug
